version: '3'

services:
  movieapp:
    image: movieapp 
    build:
       context: ./src/web
       dockerfile: Dockerfile
    container_name: movieappweb
    restart: unless-stopped
    ports:
      - 8080:5000
    volumes:
      - appdata:/var/www
    depends_on:
      - mongodb
    networks:
      - movieappfrontend
networks: 
    movieappnetwork: