version: '3.4'

services:
  movieapp:
    image: movieapp
    build:
      context: ./src/web
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  movieapi:
    image: movieapi
    build:
      context: ./src/api
      dockerfile: Dockerfile
    ports:
      - "5001:5001"