version: '2.1'

services:
  movieapp:
    image: movieapp 
    build:
       context: ./src/web
       dockerfile: Dockerfile
    environment:
        - movieapp=/src/web/app.py
    ports:
      - 8080:5000
    networks:
       movieappnetwork:
            aliases:
                - movieapp
networks: 
    movieappnetwork: