version: '3'

services:
  movieapp:
    image: movieapp 
    build:
       context: ./src/web
       dockerfile: Dockerfile
    container_name: movieappweb
    # restart: unless-stopped
    volumes:
      - appdata:/app
    networks:
      - movieappfrontend
volumes:
  appdata:
    driver: local
networks:
  movieappfrontend:
    driver: bridge
