version: '3'

services:
  movieapp:
    environment: 
      APP_ENV: "dev"
      APP_DEBUG: "True"
      APP_PORT: 5000
      MONGODB_DATABASE: flaskdb
      MONGODB_USERNAME: flaskuser
      MONGODB_PASSWORD: example123!
      MONGODB_HOSTNAME: mongodb
    ports:
      - 8080:5000

  
