version: '3.4'

services:
  movieapp:
    environment:
      - MOVIEAPIURL=http://movieapi:5001/
      - FLASK_ENV=development
  movieapi:
    environment:
      - MONGO_DBNAME=movies
      - MONGO_URI=mongodb://mongodb:27017/
      - FLASK_ENV=development

