apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-seed
  name: mongo-seed
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo-seed
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: mongo-seed
    spec:
      containers:
      - image: mongo-seed
        imagePullPolicy: ""
        name: mongo-seed
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
